name: Loyalty_client
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.5+12


environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  background_fetch: '^0.2.0'
  cupertino_icons: ^0.1.2
  curved_navigation_bar: 0.2.0
  barcode_flutter: ^1.0.0
  datetime_picker_formfield: ^0.1.8
  http: any
  shared_preferences: 0.5.3+1
  fluttertoast: ^2.0.7
  flutter_launcher_icons: "^0.7.0"
  url_launcher: ^5.0.2
  flutter_local_notifications:
  sqflite:
  path:
  path_provider:
  webview_flutter: ^0.3.15+1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/leoclub_icon_launcher.png"
  android: "launcher_icon"
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/prijava_logo.png
    - assets/images/prijava_logo_polleo.png
    - assets/images/akcije.png
    - assets/fragment_icon/fragment_akcije_logo.png
    - assets/images/registriraj_logo.png
    - assets/images/polleo.jpeg
    - assets/images/kupon_fragment_slika.PNG
    - assets/images/nema_sadrzaja.PNG
    - assets/icon/leoclub_icon_launcher.png


  #images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
