/// Flutter icons MyBarcode
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyBarcode
///      fonts:
///       - asset: fonts/MyBarcode.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyBarcode {
  MyBarcode._();

  static const _kFontFam = 'MyBarcode';

  static const IconData barcode = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData rotate = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData transaction = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData voucher = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData offers = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData wallet = const IconData(0xe806, fontFamily: _kFontFam);
}
